### PR TITLE
trying osx-arm

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@maresb @adamgayoso this should be all good to go

**Comment by maresb** [comment]
Thanks so much @ngam!!! Can I add you here as maintainer?

**Comment by adamgayoso** [comment]
getting this error

```
  File "/opt/homebrew/Caskroom/miniconda/base/envs/scvi-tools-official/lib/python3.9/site-packages/chex/_src/asserts.py", line 32, in <module>
    import tree as dm_tree
  File "/opt/homebrew/Caskroom/miniconda/base/envs/scvi-tools-official/lib/python3.9/site-packages/tree/__init__.py", line 40, in <module>
    from tree import _tree
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/scvi-tools-official/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/Caskroom/miniconda/base/envs/scvi-tools-official/lib/python3.9/site-packages/tree/_tree.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_tree.cpython-39-darwin.so' (no such file), '/usr/lib/_tree.cpython-39-darwin.so' (no such file)
```

**Comment by adamgayoso** [comment]
Actually fresh env and fresh install works....

**Comment by adamgayoso** [comment]
Confirmed again that it indeed fails. Installed the correct version, too:

```
  + dm-tree                               0.1.6  py39h2666b31_1          conda-forge/osx-arm64     Cached
```

**Comment by ngam** [comment]
Sorry, I didn't see this before. Let's try to fix this. It seems somewhere we have mismatched in libraries

**Pull request merged**
