### PR TITLE
build master branch without bazel

### PR DESCRIPTION
**Pull request by ngam**
reference: https://github.com/deepmind/tree/pull/58/files

steps:
1. generate patches from release 0.1.6 to current master
2. use cmake and make only

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@maresb this works, but it is a messy PR with a lot of edits. Have a look, but don't merge yet as we see if they respond to my request to release a new version https://github.com/deepmind/tree/issues/81

**Comment by maresb** [comment]
@ngam, wow, that's intense! Where did all those patches come from?

Unfortunately I don't think I can even pretend to be qualified to review this. :joy:

**Comment by ngam** [comment]
> wow, that's intense! Where did all those patches come from?

They are just all the PRs from the 0.1.6 release to the current master: `git checkout master && git format-patch tags/0.1.6` 😆 we can delete all of them once they release a new version

**Comment by adamgayoso** [comment]
@ngam I saw you closed the issue on the tree repo. Does that mean it's possible to complete this PR? Thanks!

**Comment by ngam** [comment]
Yes, we can certainly finish this PR by patching the whole thing; in fact, that's what those 20 patches I have here are for.

I closed the issue because I realized there was little chance they'd actually respond... 

Do you want me/us to do finish this PR? Please know finishing this PR will only mean making aarch64 and ppc64le available. Everything else will remain exactly the same

**Comment by maresb** [comment]
@ngam maybe we could merge this to a prerelease branch?

**Comment by ngam** [comment]
I don't see the point of merging it unless someone explicitly wants aarch64/ppc64le. OTherwise we can wait. What do you think? I am happy to start a dev branch tho

**Comment by ngam** [comment]
@adamgayoso do you have a need for either aarch64 or ppc64le?

**Comment by adamgayoso** [comment]
I would like it to work on apple m1, which would be arm64?

**Comment by maresb** [comment]
@adamgayoso that's `osx-arm64` which is different. I'm not sure whether or not @ngam's fix is applicable. But to track that I just added #23.

**Comment by ngam** [comment]
Okay, so sorry I wasn't keeping track of the other one.

So the issue may be that bazel doesn't cross-compile. I believe that's the problem. If so, this PR will definitely resolve it. Would you be willing to test it on m1 macs soon? I will put this in a dev branch and we can take it from there. I will give you the instructions to install it

**Comment by maresb** [comment]
@ngam, I have no mac, so hopefully @adamgayoso can test.

**Comment by adamgayoso** [comment]
Yes I can test if you are able to provide the instructions.

**Comment by ngam** [comment]
> @ngam, I have no mac, so hopefully @adamgayoso can test.

I have two m1 macs myself lol I should have tested this last time, but my bad

**Comment by ngam** [comment]
Okay, I accidentally got this uploaded on the usual place... I will mark those as broken, but for now, you could test them as this:

```
mamba create -n test dm-tree -c cf-staging
```

```
(test) ~$ python
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14) 
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tree
>>> 
>>> 

```

```
dm-tree                   0.1.6            py39h2666b31_2    cf-staging

```

**Comment by ngam** [comment]
Note the _2 in `py39h2666b31_2` --- that's this PR. It went up through the dev branch here

**Comment by ngam** [comment]
It was built in here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=488817&view=logs&j=c35410bf-a820-56fd-e231-d3cd4bead63c

@maresb could you help me decide if I should remove these (the _2 builds) from the main channel? I think we should, but now that I made the mistake, you get to confirm ...

**Comment by ngam** [comment]
Could you do a more substantial test btw to confirm this is good to go?

**Comment by ngam** [comment]
For the dev release, we usually will use:

```
mamba create -n test dm-tree -c conda-forge/label/dm-tree_dev -c cf-staging
```

This also works now. The `-c cf-staging` is for stuff that hasn't made it to the proper channels yet because of the delay. Packages get copied from cf-staging to conda-forge in a few hours and it could be dropped then


```
dating specs:

   - dm-tree


  Package              Version  Build               Channel                                       Size
────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────────

  + bzip2                1.0.8  h3422bc3_4          conda-forge/osx-arm64                       Cached
  + ca-certificates  2021.10.8  h4653dfc_0          conda-forge/osx-arm64                       Cached
  + dm-tree              0.1.6  py310h3f63c94_2     conda-forge/label/dm-tree_dev/osx-arm64      152kB
  + libcxx              13.0.1  h6a5c8ee_0          conda-forge/osx-arm64                       Cached
  + libffi               3.4.2  h3422bc3_5          conda-forge/osx-arm64                       Cached
  + libzlib             1.2.11  h90dfc92_1014       conda-forge/osx-arm64                       Cached
  + ncurses                6.3  h07bb92c_1          conda-forge/osx-arm64                       Cached
  + openssl              3.0.2  h90dfc92_1          conda-forge/osx-arm64                       Cached
  + pip                 22.0.4  pyhd8ed1ab_0        conda-forge/noarch                          Cached
  + python              3.10.4  h14b404e_0_cpython  conda-forge/osx-arm64                         13MB
  + python_abi            3.10  2_cp310             conda-forge/osx-arm64                          4kB
  + readline               8.1  hedafd6a_0          conda-forge/osx-arm64                       Cached
  + setuptools          62.0.0  py310hbe9552e_0     conda-forge/osx-arm64                       Cached
  + sqlite              3.37.1  h7e3ccbd_0          conda-forge/osx-arm64                       Cached
  + tk                  8.6.12  he1e0b03_0          conda-forge/osx-arm64                       Cached
  + tzdata               2022a  h191b570_0          conda-forge/noarch                          Cached
  + wheel               0.37.1  pyhd8ed1ab_0        conda-forge/noarch                          Cached
  + xz                   5.2.5  h642e427_1          conda-forge/osx-arm64                       Cached
  + zlib                1.2.11  h90dfc92_1014       conda-forge/osx-arm64                       Cached

  Summary:

  Install: 19 packages

  Total download: 13MB
```

**Comment by ngam** [comment]
I also ran our main test and things seem to work fine:

```
(test) ~$ python -m unittest tree.tree_test tree.tree_benchmark
.............................................Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
........WARNING:root:The use of `check_types` is deprecated and does not have any effect.
..WARNING:root:The use of `check_types` is deprecated and does not have any effect.
.WARNING:root:The use of `check_types` is deprecated and does not have any effect.
.WARNING:root:The use of `check_types` is deprecated and does not have any effect.
.WARNING:root:The use of `check_types` is deprecated and does not have any effect.
............
----------------------------------------------------------------------
Ran 70 tests in 0.022s

OK

```

**Comment by adamgayoso** [comment]
@ngam works for me as a dependency in our package!

**Comment by maresb** [comment]
@ngam let's mark them as broken, as they haven't even hit the CDN yet

**Comment by maresb** [comment]
I'm not so experienced with retractions, and I'm saying "mark them as broken" somewhat informally. I'm not sure if that's exactly the best procedure, but I would guess so. I'll be away for a few hours...

**Comment by ngam** [comment]
> I'm not so experienced with retractions, and I'm saying "mark them as broken" somewhat informally. I'm not sure if that's exactly the best procedure, but I would guess so. I'll be away for a few hours...

Pls see https://github.com/conda-forge/admin-requests/pull/426

**Comment by maresb** [comment]
Wow, that was super quick! Thanks for digging into that!

**Comment by maresb** [comment]
Another possibility would be to just change the label.

I think I made the same mistake at some point, and someone from core changed the label for me. I'm not sure how to do that myself. My first guess would be a [repodata patch](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/main/recipe), but I only see them modifying the pins and not the labels.

Or maybe core simply has admin access and can modify the labels directly.

**Comment by ngam** [comment]
> Another possibility would be to just change the label.
> 
> I think I made the same mistake at some point, and someone from core changed the label for me. I'm not sure how to do that myself. My first guess would be a [repodata patch](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/main/recipe), but I only see them modifying the pins and not the labels.
> 
> Or maybe core simply has admin access and can modify the labels directly.

It's okay, now they're marked as broken. This is the command to get them from the dev channel: 

```
mamba create -n test dm-tree -c conda-forge/label/dm-tree_dev
```

**Comment by ngam** [comment]
Continuing in #25 (adding pypy builds too)

**Pull request closed without merging**
